### PR TITLE
Link back to the GitHub Project in the footer

### PR DESCRIPTION
**Pull request by Teddochi**
Hi, first time contributor here.  I thought I'd give issue #47 a try.  Hope this helps!

It should look like this.
yelp_pull_pic

### CODE REVIEW

**Comment by ajm188** [comment]
Thanks for the pull request! I'd like @kentwills to take a look before merging, though

**Comment by kentwills** [comment]
@Teddochi Thanks for the contribution! 

Since we have bootstrap loaded on the page, let's leverage use of a [bootstrap-social](https://lipis.github.io/bootstrap-social/) icon rather than upload a GitHub image to the repository.  What do you think?

**Comment by kentwills** [comment]
@Teddochi Thanks for the contribution!

Do you think you can come up with a way that we could provide this image on the page without uploading it to the repository, maybe through a CDN?

**Comment by Teddochi** [comment]
@kentwills I'll see what I can do.  Thanks for the tip!

**Comment by kentwills** [comment]
@Teddochi looking good! Could you update the photo to show what it looks like and [squash your history](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit)?  After that we should be good to take in the request!

**Comment by ajm188** [comment]
@kentwills you can squash and merge from the github UI

**Comment by Teddochi** [comment]
@kentwills I have updated the photo and squashed my commit history.  Let me know if there is anything else I can do!

**Comment by kentwills** [comment]
TIL, @Teddochi Thanks looks great!

**Pull request merged**
