### PR TITLE
Fixes js to work when metadata isn't present

### PR DESCRIPTION
**Pull request by ajm188**
This addresses #36 

Please tell me how to write react correctly :P

### CODE REVIEW

**Comment by kentwills** [comment]
@ajm188 maybe we should write a test for this to verify functionality.  I can help out with this if you would like.

**Comment by ajm188** [comment]
@kentwills sg2m, i'll swing by in a bit

**Comment by kentwills** [comment]
@adityavohra7 is better suited to evaluate this review :)

**Comment by kentwills** [comment]
Closing this since it is outdated, feel free to re-open if you want to evaluate with the current master.

**Pull request closed without merging**
